@host = http://localhost:3000

GET {{host}}/api/posts/author

###
GET {{host}}/api/posts

###
GET {{host}}/api/posts/11

###
POST {{host}}/api/posts
Content-Type: application/json

{
   "title": "The benefits of daily exercise",
    "description": "Discover the amazing health benefits of daily exercise in this informative post.",
    "creation_date": "2023-04-28",
    "category": "Health",
    "author_id": 2
}
###
PUT {{host}}/api/posts/11
Content-Type: application/json

{
   "title": "The benefits of daily exercise",
    "description": "Discover the amazing health benefits of daily exercise in this informative post.",
    "creation_date": "2023-04-30",
    "category": "Health",
    "author_id": 4
}

###
DELETE {{host}}/api/posts/11

###
GET {{host}}/api/authors

###
GET {{host}}/api/authors/6

###
POST {{host}}/api/authors
Content-Type: application/json

{
   "name": "John1 Smith",
    "email": "johnsmith1@example.com",
    "image": "https://randomuser.me/api/portraits/men/1.jpg"
}
###
PUT {{host}}/api/authors/6
Content-Type: application/json

{
   "name": "John2 Smith",
    "email": "johnsmith1@example.com",
    "image": "https://randomuser.me/api/portraits/men/1.jpg"
}
###
DELETE {{host}}/api/authors/6